#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.A8F{1,0,7.3,1
#
app.xa8fg: package/cfg/app.xa8fg.mak

clean::
	-$(RM) package/cfg/app.xa8fg.mak
