/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      550.0,                                       
            catalogName:    "ti.catalog.arm.cortexa8",
            deviceName:     "AM3359",
            customMemoryMap:
           [          
                ["OCMC_SRAM", 
                     {
                        name: "OCMC_SRAM",
                        base: 0x40300000,                    
                        len: 0x00010000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["SRAM_LO", 
                     {
                        name: "SRAM_LO",
                        base: 0x402f0000,                    
                        len: 0x00000400,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["SRAM_HI", 
                     {
                        name: "SRAM_HI",
                        base: 0x402f0400,                    
                        len: 0x0000fc00,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR3", 
                     {
                        name: "DDR3",
                        base: 0x80000000,                    
                        len: 0x20000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],

    });
    
instance :
    
    override config string codeMemory  = "DDR3";   
    override config string dataMemory  = "DDR3";                                
    override config string stackMemory = "DDR3";

}
